const pool = require('./db');
const today = new Date().toISOString().slice(0, 10);

const stores = [
  {
    id: 1,
    name: 'カフェもーぶ',
    address: '東京都新宿区西新宿2-11-1',
    price: '¥¥',
    latitude: 35.6895,
    longitude: 139.6917,
    genre: 'カフェ',
    reason: '落ち着いた空間でゆっくりできる',
    created_on: today,
    modified_on: today,
  },
  {
    id: 2,
    name: '焼肉たんたん',
    address: '東京都新宿区西新宿2-10-1',
    price: '¥¥¥',
    latitude: 35.6898,
    longitude: 139.6921,
    genre: '焼肉',
    reason: 'お肉がとろけるほど美味しい',
    created_on: today,
    modified_on: today,
  },
  {
    id: 3,
    name: 'うどん一番',
    address: '東京都新宿区西新宿2-10-2',
    price: '¥',
    latitude: 35.6893,
    longitude: 139.6912,
    genre: '和食',
    reason: '手打ちうどんが絶品',
    created_on: today,
    modified_on: today,
  },
  {
    id: 4,
    name: 'ピザボーイ',
    address: '東京都新宿区西新宿2-10-3',
    price: '¥¥',
    latitude: 35.6897,
    longitude: 139.6923,
    genre: 'イタリアン',
    reason: '薪窯で焼いた本格ピザ',
    created_on: today,
    modified_on: today,
  },
  {
    id: 5,
    name: 'ハンバーガーパラダイス',
    address: '東京都新宿区西新宿2-10-4',
    price: '¥¥',
    latitude: 35.6894,
    longitude: 139.6915,
    genre: 'アメリカン',
    reason: 'ボリューム満点のバーガー',
    created_on: today,
    modified_on: today,
  },
  {
    id: 6,
    name: 'ラーメン龍',
    address: '東京都新宿区西新宿2-10-5',
    price: '¥',
    latitude: 35.6892,
    longitude: 139.6919,
    genre: 'ラーメン',
    reason: '濃厚とんこつスープ',
    created_on: today,
    modified_on: today,
  },
  {
    id: 7,
    name: 'フレンチ食堂ルミエール',
    address: '東京都新宿区西新宿2-10-6',
    price: '¥¥¥',
    latitude: 35.6896,
    longitude: 139.6922,
    genre: 'フレンチ',
    reason: 'おしゃれな空間で本格フレンチ',
    created_on: today,
    modified_on: today,
  },
  {
    id: 8,
    name: 'おにぎり専門店こむすび',
    address: '東京都新宿区西新宿2-10-7',
    price: '¥',
    latitude: 35.6890,
    longitude: 139.6916,
    genre: '和食',
    reason: '具だくさんのおにぎりが人気',
    created_on: today,
    modified_on: today,
  },
  {
    id: 9,
    name: 'カレー屋ジョニー',
    address: '東京都新宿区西新宿2-10-8',
    price: '¥¥',
    latitude: 35.6889,
    longitude: 139.6913,
    genre: 'カレー',
    reason: 'スパイスが効いた本格派',
    created_on: today,
    modified_on: today,
  },
  {
    id: 10,
    name: 'とんかつ武蔵',
    address: '東京都新宿区西新宿2-10-9',
    price: '¥¥',
    latitude: 35.6891,
    longitude: 139.6920,
    genre: '和食',
    reason: 'サクサク衣とジューシー肉',
    created_on: today,
    modified_on: today,
  },
  {
    id: 11,
    name: 'ベジタブルキッチン菜',
    address: '東京都新宿区西新宿2-10-10',
    price: '¥¥',
    latitude: 35.6894,
    longitude: 139.6924,
    genre: 'ヘルシー',
    reason: '野菜中心で身体にやさしい',
    created_on: today,
    modified_on: today,
  },
  {
    id: 12,
    name: 'パスタの森',
    address: '東京都新宿区西新宿2-10-11',
    price: '¥¥',
    latitude: 35.6888,
    longitude: 139.6911,
    genre: 'イタリアン',
    reason: 'もちもち生パスタが絶品',
    created_on: today,
    modified_on: today,
  },
  {
    id: 13,
    name: '中華料理 龍華',
    address: '東京都新宿区西新宿2-10-12',
    price: '¥¥',
    latitude: 35.6887,
    longitude: 139.6918,
    genre: '中華',
    reason: '本場の味が楽しめる中華',
    created_on: today,
    modified_on: today,
  },
  {
    id: 14,
    name: 'ビストロひつじ',
    address: '東京都新宿区西新宿2-10-13',
    price: '¥¥¥',
    latitude: 35.6886,
    longitude: 139.6921,
    genre: 'ビストロ',
    reason: 'ジビエ料理と自然派ワイン',
    created_on: today,
    modified_on: today,
  }
];

async function insertStores() {
  const conn = await pool.getConnection();
  try {
    for (const store of stores) {
      await conn.query(
        `INSERT INTO stores (id, name, address, price, latitude, longitude, genre, reason, created_on, modified_on)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          store.id,
          store.name,
          store.address,
          store.price,
          store.latitude,
          store.longitude,
          store.genre,
          store.reason,
          store.created_on,
          store.modified_on,
        ]
      );
    }
    console.log('✅ 店舗データ挿入完了');
  } finally {
    conn.release();
  }
}

module.exports = insertStores;
